### ISSUE TITLE
Registers as success even when an EXPECT_CALL fails

### ISSUE THREAD

**Issue by tompiercen** [jonah512/jomock#2]
Thank you very much! This library has a really nice set of functionality which I missed in gmock. I just started to experiment with jomock and observed that tests seem to register as success even when an EXPECT_CALL fails. I also added a gmock test (OrderTest.Fill) without using jomock to check the behaviour there.

[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from OrderTest
[ RUN      ] OrderTest.Fill

GMOCK WARNING:
order.cpp:44: Too few actions specified in EXPECT_CALL(warehouse, hasInventory(50, "Talisker"))...
Expected to be called twice, but has only 1 WillOnce().order.cpp:44: Failure
Actual function call count doesn't match EXPECT_CALL(warehouse, hasInventory(50, "Talisker"))...
         Expected: to be called twice
           Actual: called once - unsatisfied and active
[  FAILED  ] OrderTest.Fill (0 ms)
[----------] 1 test from OrderTest (0 ms total)

[----------] 1 test from example
[ RUN      ] example.sum_zero
[       OK ] example.sum_zero (0 ms)
[----------] 1 test from example (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OrderTest.Fill

 1 FAILED TEST
 Failure
Actual function call count doesn't match EXPECT_CALL(*::jomock::MockerCreator::getJoMock<::jomock::TypeForUniqMocker<0>>(aMaster_initialize, "aMaster_initialize"), stubFunc())...
         Expected: to be called twice

**Comment by jonah512** [comment]
Please share the code example for this failure case. 
OS?
Compiler?
non-virtual function? and so on..

**Comment by tompiercen** [comment]
The mocked functions are a set of free functions. 
The calling code is:
```
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <jomock.h>

#include <Master/Sm/MasterSm.h>


TEST(MasterSM, init)
{
    EXPECT_CALL(JOMOCK(aMaster_initialize), JOMOCK_FUNC()).Times(testing::Exactly(2));
	MasterVSInitAll();
}
```
OS: Ubuntu 20.04
Compiler: gcc 9.3

**Comment by tompiercen** [comment]
Same behaviour on Windows 10 with VS2019

**Comment by sonixground** [comment]
from your first report, "hasInventory" method called once with argument, (50, "Talisker").
please check the second method call has different argument and you also specify the argument in the JOMOCK_FUNC with (50, "Talisker") only.. then gmock's error code can be displayed like that. 

for the second case.. 
is the MasterSm an external library? can you share how the "aMaster_initialize" function is declared?

**Comment by tompiercen** [comment]
[UnitTesting.zip](https://github.com/jonah512/jomock/files/7925597/UnitTesting.zip)
I have created a minimal cmake project to show my observations.
The expected behaviour is that both tests fail.

**Comment by jonah512** [comment]
I just got the result of your test code in vs2019

![result0](https://user-images.githubusercontent.com/58866104/150800415-14cdc25b-7a0c-4c66-bfbc-9fd55923aee5.PNG)

First of all, 
It seems that the target methos are not called twice. 
```
TEST(MasterSM, init)
{
    EXPECT_CALL(JOMOCK(aMaster_initialize), JOMOCK_FUNC()).Times(testing::Exactly(2)); // should be Exactly(1) 
	MasterVSInitAll();
}
```
and... 
```
    EXPECT_CALL(warehouse, hasInventory(50, "Talisker"))
        .Times(2) // should be .Times(1)
        .WillOnce(Return(true));
```

After changing it to "1" result is clean.

![result](https://user-images.githubusercontent.com/58866104/150799944-df9a5b7e-5923-4b76-bf3a-71e1dade4732.PNG)

**Comment by jonah512** [comment]
[vs2019_example (2).zip](https://github.com/jonah512/jomock/files/7926234/vs2019_example.2.zip)

**Comment by jonah512** [comment]
Call hierarchy is as below:
```
OrderTest.Fill -> 
       order.fill -> 
               warehouse.hasInventory (return true) -> 
                       warehouse.remove -> 
                       mailService.send ->
               return
        return
return
```

**Comment by tompiercen** [comment]
I have just added the OrderTest to show that gmock without jomock gives the expected results.
When the OrderTest is fixed, I get wrongly two passed tests even though the method aMaster_initialize was not called twice:
![image](https://user-images.githubusercontent.com/11460035/150805184-c52a566e-a4ed-4e65-948c-aea21c8f083c.png)

**Comment by jonah512** [comment]
add clear function at the end of JOMOCK test. 
```
TEST(MasterSM, init)
{
    EXPECT_CALL(JOMOCK(aMaster_initialize), JOMOCK_FUNC()).Times(testing::Exactly(2));
	MasterVSInitAll();
	CLEAR_JOMOCK();
}
```

then you can get the right result as below
![result2](https://user-images.githubusercontent.com/58866104/150814344-1fdf20dc-0d3d-4569-bedd-80f16bd3bcdb.PNG)

**Comment by tompiercen** [comment]
Thank you very much! This does the job.
