### ISSUE TITLE
Illegal instruction raised when running on ARM

### ISSUE THREAD

**Issue by danielhalati** [jonah512/jomock#8]
Hello. I am trying to integrate your code inside my tests. On Linux amd64  everything works fine with -O0 and -fno-inline flags

I am using C++17 

On the other hand, on ARM, I receive Illegal Instruction

CMAKE_C_FLAGS_INIT            -march=armv8-a -mtune=cortex-a73.cortex-a53 -fPIC -fmessage-length=0 -Wall  -Wno-deprecated-declarations -Wno-parentheses -Wno-misleading-indentation     -Werror=missing-include-dirs -O3 -ftree-vectorize -ffast-math -fopenmp

I am running the ARM binaries using QEMU

Compiler version:
gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

As a first guess it seems the memory is messed up and it tries to execute some operation that doesn't exist

**Comment by jiayang-zheng** [comment]
I met the same issue on aarch64 platform. It seems the mock does not work and the unit test run into the origin logic.

**Comment by sonixground** [comment]
Please try this branch : fix_debugging_option (https://github.com/jonah512/jomock/tree/fix_debugging_option)
You need set debugging option.

**Comment by jonah512** [comment]
Example code is working with debugging option.
You guys need to check it on your code. 

Mine : 
gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by jonah512** [comment]
New branch was tested only for ARM64 and just merged. 
It is working with "ARM64_SUPPORT" definition added in CMakeFiles.txt.
